name: BUILD)Content-editor

on: workflow_dispatch

jobs:
  build:
    name: Build APP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1 
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: 'mastory.io'
            app-name: 'dokku-content-editor'
