name: Deploy content-editor

on: workflow_dispatch
  branches:
    - master
    - dev

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - id: deploy
        name: Deploy DEV to Dokku
        uses: idoberko2/dokku-deploy-github-action@v1 
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: 'mastory.io'
            app-name: 'dokku-content-editor'
