name: (DEV) content-editor

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1 
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            remote-branch: 'develop'
            dokku-host: 'mastory.io'
            app-name: 'dev-content'
