name: (DEV) content-editor

on: workflow_dispatch

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - id: deploy
        name: DEV:Deploy content-editor
        uses: vitalyliber/dokku-github-action@v6.0
        env:
          PRIVATE_KEY:  ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: 217.160.175.41
          PROJECT: dev-content-editor
          APP_CONFIG: NODE_ENV=development NPM_CONFIG_PRODUCTION=false 
