name: DESTROY)Content-editor

on: workflow_dispatch

jobs:
  build:
    name: Destroy APP
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ps axf
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          CI: true 



        
