name: (DEV) content-editor

on: workflow_dispatch

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - id: deploy
        name: DEV:Deploy content-editor
        uses: idoberko2/dokku-deploy-github-action@v1
        env:
          NODE_ENV: development
          NPM_CONFIG_PRODUCTION: false
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: 'mastory.io'
            app-name: 'dev-content-editor'
