name: (DEV) content-editor

on: workflow_dispatch

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - id: deploy
        name: DEV:Deploy content-editor
        uses: vitalyliber/dokku-github-action@v6.0
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: mastory.io
          PROJECT: dev-content-editor
          APP_CONFIG: NODE_ENV=development NPM_CONFIG_PRODUCTION=false 
