name: DESTROY)Content-editor

on: workflow_dispatch

jobs:
  build:
    name: Destroy APP
    runs-on: ubuntu-latest
    steps:
      - name: SSH Preset
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SSH
        run: ssh dokku@mastory.io 'dokku apps:list'
        
