name: DESTROY)Content-editor

on: workflow_dispatch

jobs:
  build:
    name: Destroy APP
    runs-on: ubuntu-latest
    steps:
      - name: CleanUp Letsencrypt
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            letsencrypt:cleanup ${{ secrets.PROD_CONTENT_EDITOR_NAME }}      
    
      - name: Destroy APP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            apps:destroy ${{ secrets.PROD_CONTENT_EDITOR_NAME }} --force
      
     
