name: DESTROY)Content-editor

on: workflow_dispatch

jobs:
  build:
    name: Destroy APP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} dokku@mastory.io 'dokku apps:list'
