name: Deploy content-editor

on: workflow_dispatch

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install
      - name: Serve with hot reload at localhost:3000
        run: npm run dev
      - name: Build for production
        run: npm run build
      - name: Launch server
        run: npm run start
      - name: Generate static project
        run: npm run generate

      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1 
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: 'mastory.io'
            app-name: 'dokku-content-editor'
