name: DESTROY)Content-editor

on: workflow_dispatch

jobs:
  build:
    name: Destroy APP
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: pwd && ps axf && whoami && docker ps 



        
