name: REQ)Content-editor

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build APP
    runs-on: ubuntu-latest
    steps:
      - name: GIT checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - id: deploy
        name: Deploy APP to dokku
        uses: idoberko2/dokku-deploy-github-action@v1 
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: ${{ secrets.HOSTNAME }}
            app-name: ${{ secrets.PROD_CONTENT_EDITOR_NAME }}
            remote-branch: master
            git-push-flags: --set-upstream --force
